service:
  name: instagram-serverless

plugins:
  - serverless-webpack

provider:
  name: aws
  region: eu-west-1
  stage: dev
  runtime: nodejs10.x
  tags:
    project: instagram

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Scan"
      Resource: "*"

functions:
  signUpChecksHandler:
    handler: src/functions/signup/signup.signUpChecksHandler
  signUpHandler:
    handler: src/functions/signup/signup.signUpHandler
  confirmSignUpHandler:
    handler: src/functions/confirm-signup/confirm-signup.confirmSignUpHandler
  loginHandler:
    handler: src/functions/login/login.loginHandler
  storeLoginTokensHandler:
    handler: src/functions/tokens/tokens.storeLoginTokensHandler
    events:
      - http:
          path: /store-login-tokens
          method: post
          cors: true

resources:
  Resources:
    UserTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: INS-USERS
